/**
 * @fileoverview gRPC-Web generated client stub for librarymanagement
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.2
// source: author.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.librarymanagement = require('./author_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.AuthorServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.AuthorServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.AuthorSearchRequest,
 *   !proto.librarymanagement.AuthorListResponse>}
 */
const methodDescriptor_AuthorService_GetAuthors = new grpc.web.MethodDescriptor(
  '/librarymanagement.AuthorService/GetAuthors',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.AuthorSearchRequest,
  proto.librarymanagement.AuthorListResponse,
  /**
   * @param {!proto.librarymanagement.AuthorSearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.AuthorListResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.AuthorSearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.AuthorListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.AuthorListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.AuthorServiceClient.prototype.getAuthors =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.AuthorService/GetAuthors',
      request,
      metadata || {},
      methodDescriptor_AuthorService_GetAuthors,
      callback);
};


/**
 * @param {!proto.librarymanagement.AuthorSearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.AuthorListResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.AuthorServicePromiseClient.prototype.getAuthors =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.AuthorService/GetAuthors',
      request,
      metadata || {},
      methodDescriptor_AuthorService_GetAuthors);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.AuthorGetRequest,
 *   !proto.librarymanagement.AuthorGetResponse>}
 */
const methodDescriptor_AuthorService_GetAuthor = new grpc.web.MethodDescriptor(
  '/librarymanagement.AuthorService/GetAuthor',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.AuthorGetRequest,
  proto.librarymanagement.AuthorGetResponse,
  /**
   * @param {!proto.librarymanagement.AuthorGetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.AuthorGetResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.AuthorGetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.AuthorGetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.AuthorGetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.AuthorServiceClient.prototype.getAuthor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.AuthorService/GetAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_GetAuthor,
      callback);
};


/**
 * @param {!proto.librarymanagement.AuthorGetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.AuthorGetResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.AuthorServicePromiseClient.prototype.getAuthor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.AuthorService/GetAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_GetAuthor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.CreateAuthorRequest,
 *   !proto.librarymanagement.AuthorResponse>}
 */
const methodDescriptor_AuthorService_CreateAuthor = new grpc.web.MethodDescriptor(
  '/librarymanagement.AuthorService/CreateAuthor',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.CreateAuthorRequest,
  proto.librarymanagement.AuthorResponse,
  /**
   * @param {!proto.librarymanagement.CreateAuthorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.AuthorResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.CreateAuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.AuthorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.AuthorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.AuthorServiceClient.prototype.createAuthor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.AuthorService/CreateAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_CreateAuthor,
      callback);
};


/**
 * @param {!proto.librarymanagement.CreateAuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.AuthorResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.AuthorServicePromiseClient.prototype.createAuthor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.AuthorService/CreateAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_CreateAuthor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.UpdateAuthorRequest,
 *   !proto.librarymanagement.AuthorResponse>}
 */
const methodDescriptor_AuthorService_UpdateAuthor = new grpc.web.MethodDescriptor(
  '/librarymanagement.AuthorService/UpdateAuthor',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.UpdateAuthorRequest,
  proto.librarymanagement.AuthorResponse,
  /**
   * @param {!proto.librarymanagement.UpdateAuthorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.AuthorResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.UpdateAuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.AuthorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.AuthorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.AuthorServiceClient.prototype.updateAuthor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.AuthorService/UpdateAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_UpdateAuthor,
      callback);
};


/**
 * @param {!proto.librarymanagement.UpdateAuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.AuthorResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.AuthorServicePromiseClient.prototype.updateAuthor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.AuthorService/UpdateAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_UpdateAuthor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.AuthorDeleteRequest,
 *   !proto.librarymanagement.DeleteResponse>}
 */
const methodDescriptor_AuthorService_DeleteAuthor = new grpc.web.MethodDescriptor(
  '/librarymanagement.AuthorService/DeleteAuthor',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.AuthorDeleteRequest,
  proto.librarymanagement.DeleteResponse,
  /**
   * @param {!proto.librarymanagement.AuthorDeleteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.DeleteResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.AuthorDeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.DeleteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.DeleteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.AuthorServiceClient.prototype.deleteAuthor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.AuthorService/DeleteAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_DeleteAuthor,
      callback);
};


/**
 * @param {!proto.librarymanagement.AuthorDeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.DeleteResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.AuthorServicePromiseClient.prototype.deleteAuthor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.AuthorService/DeleteAuthor',
      request,
      metadata || {},
      methodDescriptor_AuthorService_DeleteAuthor);
};


module.exports = proto.librarymanagement;

