/**
 * @fileoverview gRPC-Web generated client stub for librarymanagement
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.2
// source: book.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.librarymanagement = require('./book_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.BookServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.BookServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.BookSearchRequest,
 *   !proto.librarymanagement.BookListResponse>}
 */
const methodDescriptor_BookService_GetBooks = new grpc.web.MethodDescriptor(
  '/librarymanagement.BookService/GetBooks',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.BookSearchRequest,
  proto.librarymanagement.BookListResponse,
  /**
   * @param {!proto.librarymanagement.BookSearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BookListResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.BookSearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BookListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BookListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BookServiceClient.prototype.getBooks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BookService/GetBooks',
      request,
      metadata || {},
      methodDescriptor_BookService_GetBooks,
      callback);
};


/**
 * @param {!proto.librarymanagement.BookSearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BookListResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BookServicePromiseClient.prototype.getBooks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BookService/GetBooks',
      request,
      metadata || {},
      methodDescriptor_BookService_GetBooks);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.BookGetRequest,
 *   !proto.librarymanagement.BookGetResponse>}
 */
const methodDescriptor_BookService_GetBook = new grpc.web.MethodDescriptor(
  '/librarymanagement.BookService/GetBook',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.BookGetRequest,
  proto.librarymanagement.BookGetResponse,
  /**
   * @param {!proto.librarymanagement.BookGetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BookGetResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.BookGetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BookGetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BookGetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BookServiceClient.prototype.getBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BookService/GetBook',
      request,
      metadata || {},
      methodDescriptor_BookService_GetBook,
      callback);
};


/**
 * @param {!proto.librarymanagement.BookGetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BookGetResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BookServicePromiseClient.prototype.getBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BookService/GetBook',
      request,
      metadata || {},
      methodDescriptor_BookService_GetBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.CreateBookRequest,
 *   !proto.librarymanagement.BookResponse>}
 */
const methodDescriptor_BookService_CreateBook = new grpc.web.MethodDescriptor(
  '/librarymanagement.BookService/CreateBook',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.CreateBookRequest,
  proto.librarymanagement.BookResponse,
  /**
   * @param {!proto.librarymanagement.CreateBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BookResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.CreateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BookServiceClient.prototype.createBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BookService/CreateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_CreateBook,
      callback);
};


/**
 * @param {!proto.librarymanagement.CreateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BookResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BookServicePromiseClient.prototype.createBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BookService/CreateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_CreateBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.UpdateBookRequest,
 *   !proto.librarymanagement.BookResponse>}
 */
const methodDescriptor_BookService_UpdateBook = new grpc.web.MethodDescriptor(
  '/librarymanagement.BookService/UpdateBook',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.UpdateBookRequest,
  proto.librarymanagement.BookResponse,
  /**
   * @param {!proto.librarymanagement.UpdateBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BookResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.UpdateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BookServiceClient.prototype.updateBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BookService/UpdateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_UpdateBook,
      callback);
};


/**
 * @param {!proto.librarymanagement.UpdateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BookResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BookServicePromiseClient.prototype.updateBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BookService/UpdateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_UpdateBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.BookDeleteRequest,
 *   !proto.librarymanagement.DeleteResponse>}
 */
const methodDescriptor_BookService_DeleteBook = new grpc.web.MethodDescriptor(
  '/librarymanagement.BookService/DeleteBook',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.BookDeleteRequest,
  proto.librarymanagement.DeleteResponse,
  /**
   * @param {!proto.librarymanagement.BookDeleteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.DeleteResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.BookDeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.DeleteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.DeleteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BookServiceClient.prototype.deleteBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BookService/DeleteBook',
      request,
      metadata || {},
      methodDescriptor_BookService_DeleteBook,
      callback);
};


/**
 * @param {!proto.librarymanagement.BookDeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.DeleteResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BookServicePromiseClient.prototype.deleteBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BookService/DeleteBook',
      request,
      metadata || {},
      methodDescriptor_BookService_DeleteBook);
};


module.exports = proto.librarymanagement;

