/**
 * @fileoverview gRPC-Web generated client stub for librarymanagement
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.2
// source: borrowing.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.librarymanagement = require('./borrowing_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.BorrowingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.BorrowingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.BorrowBookRequest,
 *   !proto.librarymanagement.BorrowingResponse>}
 */
const methodDescriptor_BorrowingService_BorrowBook = new grpc.web.MethodDescriptor(
  '/librarymanagement.BorrowingService/BorrowBook',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.BorrowBookRequest,
  proto.librarymanagement.BorrowingResponse,
  /**
   * @param {!proto.librarymanagement.BorrowBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BorrowingResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.BorrowBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BorrowingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BorrowingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BorrowingServiceClient.prototype.borrowBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BorrowingService/BorrowBook',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_BorrowBook,
      callback);
};


/**
 * @param {!proto.librarymanagement.BorrowBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BorrowingResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BorrowingServicePromiseClient.prototype.borrowBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BorrowingService/BorrowBook',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_BorrowBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.ReturnBookRequest,
 *   !proto.librarymanagement.BorrowingResponse>}
 */
const methodDescriptor_BorrowingService_ReturnBook = new grpc.web.MethodDescriptor(
  '/librarymanagement.BorrowingService/ReturnBook',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.ReturnBookRequest,
  proto.librarymanagement.BorrowingResponse,
  /**
   * @param {!proto.librarymanagement.ReturnBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BorrowingResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.ReturnBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BorrowingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BorrowingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BorrowingServiceClient.prototype.returnBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BorrowingService/ReturnBook',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_ReturnBook,
      callback);
};


/**
 * @param {!proto.librarymanagement.ReturnBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BorrowingResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BorrowingServicePromiseClient.prototype.returnBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BorrowingService/ReturnBook',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_ReturnBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.UserBorrowingsRequest,
 *   !proto.librarymanagement.BorrowingListResponse>}
 */
const methodDescriptor_BorrowingService_GetUserBorrowings = new grpc.web.MethodDescriptor(
  '/librarymanagement.BorrowingService/GetUserBorrowings',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.UserBorrowingsRequest,
  proto.librarymanagement.BorrowingListResponse,
  /**
   * @param {!proto.librarymanagement.UserBorrowingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BorrowingListResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.UserBorrowingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BorrowingListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BorrowingListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BorrowingServiceClient.prototype.getUserBorrowings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BorrowingService/GetUserBorrowings',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_GetUserBorrowings,
      callback);
};


/**
 * @param {!proto.librarymanagement.UserBorrowingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BorrowingListResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BorrowingServicePromiseClient.prototype.getUserBorrowings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BorrowingService/GetUserBorrowings',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_GetUserBorrowings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.OverdueBooksRequest,
 *   !proto.librarymanagement.BorrowingListResponse>}
 */
const methodDescriptor_BorrowingService_GetOverdueBooks = new grpc.web.MethodDescriptor(
  '/librarymanagement.BorrowingService/GetOverdueBooks',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.OverdueBooksRequest,
  proto.librarymanagement.BorrowingListResponse,
  /**
   * @param {!proto.librarymanagement.OverdueBooksRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.BorrowingListResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.OverdueBooksRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.BorrowingListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.BorrowingListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.BorrowingServiceClient.prototype.getOverdueBooks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.BorrowingService/GetOverdueBooks',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_GetOverdueBooks,
      callback);
};


/**
 * @param {!proto.librarymanagement.OverdueBooksRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.BorrowingListResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.BorrowingServicePromiseClient.prototype.getOverdueBooks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.BorrowingService/GetOverdueBooks',
      request,
      metadata || {},
      methodDescriptor_BorrowingService_GetOverdueBooks);
};


module.exports = proto.librarymanagement;

