/**
 * @fileoverview gRPC-Web generated client stub for librarymanagement
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.2
// source: category.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js')
const proto = {};
proto.librarymanagement = require('./category_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.CategoryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.librarymanagement.CategoryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.CategorySearchRequest,
 *   !proto.librarymanagement.CategoryListResponse>}
 */
const methodDescriptor_CategoryService_GetCategories = new grpc.web.MethodDescriptor(
  '/librarymanagement.CategoryService/GetCategories',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.CategorySearchRequest,
  proto.librarymanagement.CategoryListResponse,
  /**
   * @param {!proto.librarymanagement.CategorySearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.CategoryListResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.CategorySearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.CategoryListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.CategoryListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.CategoryServiceClient.prototype.getCategories =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.CategoryService/GetCategories',
      request,
      metadata || {},
      methodDescriptor_CategoryService_GetCategories,
      callback);
};


/**
 * @param {!proto.librarymanagement.CategorySearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.CategoryListResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.CategoryServicePromiseClient.prototype.getCategories =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.CategoryService/GetCategories',
      request,
      metadata || {},
      methodDescriptor_CategoryService_GetCategories);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.CategoryTreeRequest,
 *   !proto.librarymanagement.CategoryTreeResponse>}
 */
const methodDescriptor_CategoryService_GetCategoryTree = new grpc.web.MethodDescriptor(
  '/librarymanagement.CategoryService/GetCategoryTree',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.CategoryTreeRequest,
  proto.librarymanagement.CategoryTreeResponse,
  /**
   * @param {!proto.librarymanagement.CategoryTreeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.CategoryTreeResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.CategoryTreeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.CategoryTreeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.CategoryTreeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.CategoryServiceClient.prototype.getCategoryTree =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.CategoryService/GetCategoryTree',
      request,
      metadata || {},
      methodDescriptor_CategoryService_GetCategoryTree,
      callback);
};


/**
 * @param {!proto.librarymanagement.CategoryTreeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.CategoryTreeResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.CategoryServicePromiseClient.prototype.getCategoryTree =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.CategoryService/GetCategoryTree',
      request,
      metadata || {},
      methodDescriptor_CategoryService_GetCategoryTree);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.librarymanagement.CreateCategoryRequest,
 *   !proto.librarymanagement.CategoryResponse>}
 */
const methodDescriptor_CategoryService_CreateCategory = new grpc.web.MethodDescriptor(
  '/librarymanagement.CategoryService/CreateCategory',
  grpc.web.MethodType.UNARY,
  proto.librarymanagement.CreateCategoryRequest,
  proto.librarymanagement.CategoryResponse,
  /**
   * @param {!proto.librarymanagement.CreateCategoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.librarymanagement.CategoryResponse.deserializeBinary
);


/**
 * @param {!proto.librarymanagement.CreateCategoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.librarymanagement.CategoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.librarymanagement.CategoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.librarymanagement.CategoryServiceClient.prototype.createCategory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/librarymanagement.CategoryService/CreateCategory',
      request,
      metadata || {},
      methodDescriptor_CategoryService_CreateCategory,
      callback);
};


/**
 * @param {!proto.librarymanagement.CreateCategoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.librarymanagement.CategoryResponse>}
 *     Promise that resolves to the response
 */
proto.librarymanagement.CategoryServicePromiseClient.prototype.createCategory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/librarymanagement.CategoryService/CreateCategory',
      request,
      metadata || {},
      methodDescriptor_CategoryService_CreateCategory);
};


module.exports = proto.librarymanagement;

